### ISSUE TITLE
TS2532: Object is possibly 'undefined' -- when using `faker`

### ISSUE THREAD

**Issue by robbyphillips** [CyriacBr/class-fixtures-factory#10]
Using `faker` either as 

```typescript
class Thing {
  @Fixture(faker => faker.date.future())
  date: Date
}

```
or 
```typescript
class Thing {
  @Fixture({ get: faker => faker.date.future() })
  date: Date
}
```

Throws an `Object is possibliy 'undefined'` error for the `faker` object.

This looks like it's caused by the type definition, `(faker?: Faker.FakerStatic) => string | undefined)`.  It seems like this is a mistake since the function should always receive the faker object, regardless as to whether or not it uses it.

Calling with optional chaining resolved the type issue.
```typescript
class Thing {
  @Fixture(faker => faker?.date.future())
  date: Date
}
```

**Comment by CyriacBr** [comment]
You're right, this'll be fixed.

**Comment by CyriacBr** [comment]
Fixed locally. Will be live in the next release.
