### ISSUE TITLE
Bug:  Couldn't extract the type

### ISSUE THREAD

**Issue by upMKuhn** [CyriacBr/class-fixtures-factory#20]
## Error: Couldn't extract the type of "checkId". Use @Fixture({ type: () => Foo }). 
Hi there,  
thank you for your library. I think i stumbled upon a bug. Can you have a quick look, maybe I did something wrong here.  

## Stituation

```typescript
    factory = new FixtureFactory();
    factory.register([OrderFileFake]); // works
    // factory.register([OrderFileFake, CheckFake]); // breaks

    currentOrderFile = factory
      .make(OrderFileFake)
      .with({
        order: {
          status: OrderStatus.RESULTS_PROVIDED,
          checks: [{ actor: { type: ActorType.CORPORATE } }, { actor: { type: ActorType.INDIVIDUAL } }], // works
          // checks: [].concat(CheckFake.coperateCheck(factory).many(2), CheckFake.indivdualCheck(factory).many(2)), // breaks
        },
      })
      .one();
```
## Models
```typescript
export class OrderFileFake implements IOrderFile {
  @Fixture({ type: () => OrderFake })
  public order: IOrder;

  @Fixture({ type: () => [CheckFake] })
  public checks: ICheck[];
}

export class CheckFake implements ICheck {
  @Fixture(uuid)
  public checkId: string;
}
```

Thanks!

**Comment by CyriacBr** [comment]
> export class CheckFake implements ICheck {
  @Fixture(uuid)
  public checkId: string;
}

What is `uuid` here?

**Comment by CyriacBr** [comment]
@upMKuhn Oh I guess you're trying to generate a random uuid for `CheckFake.checkId`? If so you could use faker directly.
Not sure of the correct API but it is something like that:
```js
@Fixture(faker => faker.random.uuid())
public checkId: string
```

**Comment by upMKuhn** [comment]
Hey @CyriacBr, the error message is a bit misleading. The `@Fixture(uuid)` is unrelated. It could be replaced by anything else

I think the root cause of this error message might a circular dependency situation.  Since I haven't included the entire Fixture setup. It wasn't clear in my original post:

OrderFileFake -> ICheck[] +(IOrder -> IActor). 
ICheck -> IActor. 
IActor -> ICheck.

**Comment by upMKuhn** [comment]
The best indicator for it is:  
````ts
    factory.register([OrderFileFake]); // works
    // factory.register([OrderFileFake, CheckFake]); // breaks
   
   checks: [{ actor: { type: ActorType.CORPORATE } }, { actor: { type: ActorType.INDIVIDUAL } }], // works
   // checks: [].concat(CheckFake.coperateCheck(factory).many(2), CheckFake.indivdualCheck(factory).many(2)), // breaks


````

**Comment by CyriacBr** [comment]
Going by the error message, the factory can't, for some reason find the type of `checkId`. So it is odd that explicitely setting the type (or an override value) doesn't work.
Can you show me all your entities?

If this is a relationships issue, that's probably fixed in this PR https://github.com/CyriacBr/class-fixtures-factory/pull/17.

**Comment by upMKuhn** [comment]
It hopefully will be fixed in the new PR then. 
Unfortunately I don't have the factories anymore. In any case, I can put my hand for it into the flames that its related to complex nested and circular dependencies. It became clear to me during trial and error.

**Comment by upMKuhn** [comment]
We can close here I'll watch and try again when the PR is merged.  
Thats what I remember 
OrderFile -> ICheck[] .
OrderFile -> IOrder

IOrder -> ICheck[]

ICheck -> IActor.
IActor -> ICheck.

**Comment by CyriacBr** [comment]
Alright, I'll close this.
But, could you just provide the classes at least? I'd like to test them on my end with the PR version.

**Comment by upMKuhn** [comment]
I'll try to find them again.
