### ISSUE TITLE
Use interfaces instead of classes

### ISSUE THREAD

**Issue by fpereira1** [CyriacBr/class-fixtures-factory#21]
Hi there,
Is there any way to use interfaces instead of classes on this module? If not, are you aware of a way to convert interfaces into classes programmatically?

**Comment by CyriacBr** [comment]
Hi @fpereira1.
TypeScript interfaces only exist at compile-time. At runtime (when your code is executed) they do not exist.
There's no way to retrieve interfaces during that time.
